import configparser


def _parse_bool(s: str) -> bool:
    return s.lower() == 'true'


_CONFIG_FILE = 'config.ini'

_config = configparser.ConfigParser()
_config.read(_CONFIG_FILE)


_CONFIG_SELENIUM = _config['selenium']
SELENIUM_FIREFOX_DRIVER_EXE_PATH = _CONFIG_SELENIUM['FIREFOX_DRIVER_EXE_PATH']
SELENIUM_KEEP_OPEN = _parse_bool(_CONFIG_SELENIUM['KEEP_OPEN'])

_CONFIG_BCPARKS = _config['bcparks']
BCPARKS_PARTY_SIZE = int(_CONFIG_BCPARKS['PARTY_SIZE'])
BCPARKS_TENT_PADS = int(_CONFIG_BCPARKS['TENT_PADS'])
BCPARKS_NIGHTS = int(_CONFIG_BCPARKS['NIGHTS'])
BCPARKS_RESERVATION_AREA = _CONFIG_BCPARKS['RESERVATION_AREA']
BCPARKS_RETRY_ON_RESERVE_FAIL = _parse_bool(_CONFIG_BCPARKS['RETRY_ON_RESERVE_FAIL'])
