import configparser

_CONFIG_FILE = 'config.ini'

_config = configparser.ConfigParser()
_config.read(_CONFIG_FILE)

_CONFIG_SELENIUM = _config['selenium']
SELENIUM_FIREFOX_DRIVER_EXE_PATH = _CONFIG_SELENIUM['FIREFOX_DRIVER_EXE_PATH']
SELENIUM_KEEP_OPEN = _CONFIG_SELENIUM['KEEP_OPEN'].lower() == 'true'

_CONFIG_BCPARKS = _config['bcparks']
BCPARKS_PARTY_SIZE = _CONFIG_BCPARKS['PARTY_SIZE']
BCPARKS_TENT_PADS = _CONFIG_BCPARKS['TENT_PADS']
BCPARKS_NIGHTS = _CONFIG_BCPARKS['NIGHTS']
